server:
  port: 8090

logging:
  level:
    com:
      example:
        jobscheduler: INFO
    org:
      springframework:
        scheduling: DEBUG

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh,mappings
  endpoint:
    health:
      show-details: always