@baseUrl = http://localhost:8090

### List Jobs
GET {{baseUrl}}/jobs

> {%
    client.global.set("id", response.body[0].name.split(":")[1]);
%}

### Get Job by ID
GET {{baseUrl}}/jobs/{{id}}

### Update Job by ID for PING
PUT {{baseUrl}}/jobs/{{id}}
Content-Type: Application/json

{
  "params": {
    "host": "http://google.com"
  }
}

### Start Job by ID
PUT {{baseUrl}}/jobs/{{id}}/start
Content-Type: Application/json

{
  "params": {
    "url": "http://google.com",
    "city": "Istanbul,TR"
  }
}

### Stop Job by ID
PUT {{baseUrl}}/jobs/{{id}}/stop

### List Job Triggers
GET {{baseUrl}}/jobs/triggers
