@baseUrl = http://localhost:8080

### List Jobs
GET {{baseUrl}}/jobs

> {%
    client.global.set("id", response.body[0].name.split(":")[1]);
%}

### Get Job by ID
GET {{baseUrl}}/jobs/{{id}}

### Start Job by ID for PING
PUT {{baseUrl}}/jobs/881d188d-ad01-410d-bf65-752f665ef473/start
Content-Type: Application/json

{
  "params": {
    "host": "http://google.com"
  }
}

### Start Job by ID for HttpMonitorJob
PUT {{baseUrl}}/jobs/881d188d-ad01-410d-bf65-752f665ef474/start
Content-Type: Application/json

{
  "params": {
    "url": "http://google.com"
  }
}

### Start Job by ID for TarihteBugunJob
PUT {{baseUrl}}/jobs/881d188d-ad01-410d-bf65-752f665ef475/start
Content-Type: Application/json

{
}

### Start Job by ID for WeatherInformationJob
PUT {{baseUrl}}/jobs/881d188d-ad01-410d-bf65-752f665ef476/start
Content-Type: Application/json

{
  "params": {
    "city": "Istanbul,TR"
  }
}